name: matrix configuration example
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        images: [hello-world,alpine]
        os: [ubuntu-latest,windows-latest,ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: docker info
        run: docker info
      - name: run hello world docker container
        run: docker run ${{ matrix.images }}

    
