name: ci workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}

  build-job:
    runs-on: ubuntu-latest
    needs: log-the-inputs
    steps:
      - uses: actions/checkout@v2
      - name: read the file
        run: cat README.md
      - name: list files
        run: ls -la
      - name: install cowsay library
        run: sudo apt-get install cowsay -y
      - name: generate tux messages text file with cowsay
        run: cowsay -f tux "Hellow world" > dragon.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt
  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: check for the file
        run: grep -i "world" dragon.txt
      - name: list all the files
        run: ls -lart
  deloy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: show the content of the file
        run: cat dragon.txt
