name: testing workflow filters
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - closed
        paths-ignore:
            - 'README.md'
            - '.github\**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            

