name: ci workflow 
on : 
    push:
        branches: 
        - main
        - 'feature/*'
    
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: read the file
              run: cat README.md
            - name: list files
              run: ls -la
            - name: install cowsay library
              run: sudo apt-get install cowsay -y 

            - name: generate tux messages text file with cowsay
              run: cowsay -f tux "Hellow world" > dragon.txt

            - name: read dragon.txt file
              run: cat dragon.txt

