name: ci workflow 
on : 
    push:
        branches: 
        - master
        - 'feature/*'
    
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: read the file
              run: cat README.md
            - name: list files
              run: ls -la
